name: Deploy

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build binary
        run: |
          GOOS=wasip1 GOARCH=wasm go build -o starfield.wasm ./cmd/starfield
          CGO_ENABLED=0 go build -trimpath -ldflags '-s -w' -o starfield ./cmd/starfield

      - name: Create draft release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          draft: true
          files: |
            ${{ github.workspace }}/starfield.wasm
            ${{ github.workspace }}/starfield
